General NMI Improvements
TRUMPF-IoT/cdeNMI pull request #44
Opened 2022-11-18 19:47 UTC by muenchris

2022-11-18 20:41 UTC, MarkusHorstmann requested changes

2022-11-18 20:41 UTC, MarkusHorstmann commented on src/HTML5/ExtensionPlugins/172-CDMyC3/CDMyC3/ClientBin/P172/CDMyC3.TheC3Service.js
> +            debugger;
Accidental?

2022-11-19 20:19 UTC, muenchris commented on src/HTML5/ExtensionPlugins/172-CDMyC3/CDMyC3/ClientBin/P172/CDMyC3.TheC3Service.js
> +            debugger;
renmoved

2022-11-19 20:57 UTC, MarkusHorstmann approved these changes

2022-11-19 22:27 UTC, merged